backend:
  name: git-gateway
  branch: master

media_folder: static/assets/posts
public_folder: assets
media_folder_relative: true
publish_mode: editorial_workflow

collections:
  - name: en-us-blog
    label: English Blog
    folder: content/en-us/blog
    create: true
    slug: "{{slug}}"
    fields:
      - { label: Created, name: created, widget: datetime, format: YYYY-MM-DD hh:mm:ss }
      - { label: Updated, name: updated, widget: datetime, format: YYYY-MM-DD hh:mm:ss }
      - { label: Thumb, name: thumbnail, widget: image }
      - { label: Title, name: title, widget: string }
      - { label: Description, name: description, widget: string }
      - { label: Tags, name: tags, widget: list, default: [""] }
      - { label: Body, name: body, widget: markdown }

  - name: pt-br-blog
    label: Portuguese Blog
    folder: content/pt-br/blog
    create: true
    slug: "{{slug}}"
    fields:
      - { label: Created, name: created, widget: datetime, format: YYYY-MM-DD hh:mm:ss }
      - { label: Updated, name: updated, widget: datetime, format: YYYY-MM-DD hh:mm:ss }
      - { label: Thumb, name: thumbnail, widget: image }
      - { label: Title, name: title, widget: string }
      - { label: Description, name: description, widget: string }
      - { label: Tags, name: tags, widget: list, default: [""] }
      - { label: Body, name: body, widget: markdown }
      - { label: Canonical, name: canonical, widget: "relation", collection: "en-us-blog", searchFields: ["title"], valueField: "{{ slug }}" }

  - name: "pages"
    label: "Pages"
    files:
      - name: "about en-us"
        label: "About en-us"
        file: "content/en-us/pages/about.md"
        fields: 
          - { label: Title, name: title, widget: string } 
          - { label: Description, name: description, widget: string }
          - { label: Thumb, name: thumbnail, widget: image }
          - { label: Body, name: body, widget: markdown }

      - name: "about pt-br"
        label: "About pt-br"
        file: "content/pt-br/pages/about.md"
        fields: 
          - { label: Title, name: title, widget: string } 
          - { label: Description, name: description, widget: string }
          - { label: Thumb, name: thumbnail, widget: image }
          - { label: Body, name: body, widget: markdown }
